name: CI/CD main balance-management

on:
  push:
    branches:
      - main123

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Build with Maven
        working-directory: end-project/balance-management
        run: mvn clean package -DskipTests

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t aslanovagunel/balance-management ./end-project/balance-management

      - name: Push Docker Image
        run: docker push aslanovagunel/balance-management
